// teams.js — single source of truth for all match data
// Update qualifyPct, played, next, and LAST_UPDATED here only.
// scoreboard.html and worst.html both load this file.

const LAST_UPDATED = "27 มิ.ย. 2026";

const teamByName = {
    // ── Group A ─────────────────────────────────────────────────────────────
    "South Africa": { name:"South Africa", group:"A", pot:3, qualifyPct:100,
        played:[{date:"Jun 11",vs:"Mexico",score:"0-2",wdl:"L"},{date:"Jun 18",vs:"Czechia",score:"1-1",wdl:"D"},{date:"Jun 24",vs:"South Korea",score:"1-0",wdl:"W"}],
        next:[] },
    "Mexico": { name:"Mexico", group:"A", qualifyPct:100,
        played:[{date:"Jun 11",vs:"South Africa",score:"2-0",wdl:"W"},{date:"Jun 18",vs:"South Korea",score:"1-0",wdl:"W"},{date:"Jun 24",vs:"Czechia",score:"3-0",wdl:"W"}],
        next:[] },
    "South Korea": { name:"South Korea", group:"A", qualifyPct:35,
        played:[{date:"Jun 11",vs:"Czechia",score:"2-1",wdl:"W"},{date:"Jun 18",vs:"Mexico",score:"0-1",wdl:"L"},{date:"Jun 24",vs:"South Africa",score:"0-1",wdl:"L"}],
        next:[] },
    "Czechia": { name:"Czechia", group:"A", qualifyPct:0,
        played:[{date:"Jun 11",vs:"South Korea",score:"1-2",wdl:"L"},{date:"Jun 18",vs:"South Africa",score:"1-1",wdl:"D"},{date:"Jun 24",vs:"Mexico",score:"0-3",wdl:"L"}],
        next:[] },

    // ── Group B ─────────────────────────────────────────────────────────────
    "Qatar": { name:"Qatar", group:"B", pot:3, qualifyPct:0,
        played:[{date:"Jun 12",vs:"Switzerland",score:"1-1",wdl:"D"},{date:"Jun 18",vs:"Canada",score:"0-6",wdl:"L"},{date:"Jun 24",vs:"Bosnia",score:"1-3",wdl:"L"}],
        next:[] },
    "Switzerland": { name:"Switzerland", group:"B", pot:2, qualifyPct:100,
        played:[{date:"Jun 12",vs:"Qatar",score:"1-1",wdl:"D"},{date:"Jun 18",vs:"Bosnia",score:"4-1",wdl:"W"},{date:"Jun 24",vs:"Canada",score:"3-1",wdl:"W"}],
        next:[] },
    "Canada": { name:"Canada", group:"B", qualifyPct:100,
        played:[{date:"Jun 12",vs:"Bosnia",score:"1-1",wdl:"D"},{date:"Jun 18",vs:"Qatar",score:"6-0",wdl:"W"},{date:"Jun 24",vs:"Switzerland",score:"1-3",wdl:"L"}],
        next:[] },
    "Bosnia": { name:"Bosnia", group:"B", qualifyPct:65,
        played:[{date:"Jun 12",vs:"Canada",score:"1-1",wdl:"D"},{date:"Jun 18",vs:"Switzerland",score:"1-4",wdl:"L"},{date:"Jun 24",vs:"Qatar",score:"3-1",wdl:"W"}],
        next:[] },

    // ── Group C ─────────────────────────────────────────────────────────────
    "Brazil": { name:"Brazil", group:"C", pot:1, qualifyPct:100,
        played:[{date:"Jun 13",vs:"Morocco",score:"1-1",wdl:"D"},{date:"Jun 19",vs:"Haiti",score:"3-0",wdl:"W"},{date:"Jun 24",vs:"Scotland",score:"3-0",wdl:"W"}],
        next:[] },
    "Scotland": { name:"Scotland", group:"C", pot:3, qualifyPct:20,
        played:[{date:"Jun 13",vs:"Haiti",score:"1-0",wdl:"W"},{date:"Jun 19",vs:"Morocco",score:"0-1",wdl:"L"},{date:"Jun 24",vs:"Brazil",score:"0-3",wdl:"L"}],
        next:[] },
    "Morocco": { name:"Morocco", group:"C", pot:2, qualifyPct:100,
        played:[{date:"Jun 13",vs:"Brazil",score:"1-1",wdl:"D"},{date:"Jun 19",vs:"Scotland",score:"1-0",wdl:"W"},{date:"Jun 24",vs:"Haiti",score:"4-2",wdl:"W"}],
        next:[] },
    "Haiti": { name:"Haiti", group:"C", pot:4, qualifyPct:0,
        played:[{date:"Jun 13",vs:"Scotland",score:"0-1",wdl:"L"},{date:"Jun 19",vs:"Brazil",score:"0-3",wdl:"L"},{date:"Jun 24",vs:"Morocco",score:"2-4",wdl:"L"}],
        next:[] },

    // ── Group D ─────────────────────────────────────────────────────────────
    "Australia": { name:"Australia", group:"D", pot:2, qualifyPct:100,
        played:[{date:"Jun 13",vs:"Turkey",score:"2-0",wdl:"W"},{date:"Jun 19",vs:"USA",score:"0-2",wdl:"L"},{date:"Jun 25",vs:"Paraguay",score:"0-0",wdl:"D"}],
        next:[] },
    "Turkey": { name:"Turkey", group:"D", pot:4, qualifyPct:0,
        played:[{date:"Jun 13",vs:"Australia",score:"0-2",wdl:"L"},{date:"Jun 19",vs:"Paraguay",score:"0-1",wdl:"L"},{date:"Jun 25",vs:"USA",score:"3-2",wdl:"W"}],
        next:[] },
    "Paraguay": { name:"Paraguay", group:"D", pot:3, qualifyPct:60,
        played:[{date:"Jun 12",vs:"USA",score:"1-4",wdl:"L"},{date:"Jun 19",vs:"Turkey",score:"1-0",wdl:"W"},{date:"Jun 25",vs:"Australia",score:"0-0",wdl:"D"}],
        next:[] },
    "USA": { name:"USA", group:"D", qualifyPct:100,
        played:[{date:"Jun 12",vs:"Paraguay",score:"4-1",wdl:"W"},{date:"Jun 19",vs:"Australia",score:"2-0",wdl:"W"},{date:"Jun 25",vs:"Turkey",score:"2-3",wdl:"L"}],
        next:[] },

    // ── Group E ─────────────────────────────────────────────────────────────
    "Germany": { name:"Germany", group:"E", pot:1, qualifyPct:100,
        played:[{date:"Jun 14",vs:"Curaçao",score:"7-1",wdl:"W"},{date:"Jun 20",vs:"Ivory Coast",score:"2-1",wdl:"W"},{date:"Jun 25",vs:"Ecuador",score:"1-2",wdl:"L"}],
        next:[] },
    "Ecuador": { name:"Ecuador", group:"E", pot:2, qualifyPct:65,
        played:[{date:"Jun 14",vs:"Ivory Coast",score:"0-1",wdl:"L"},{date:"Jun 20",vs:"Curaçao",score:"0-0",wdl:"D"},{date:"Jun 25",vs:"Germany",score:"2-1",wdl:"W"}],
        next:[] },
    "Curaçao": { name:"Curaçao", group:"E", pot:4, qualifyPct:0,
        played:[{date:"Jun 14",vs:"Germany",score:"1-7",wdl:"L"},{date:"Jun 20",vs:"Ecuador",score:"0-0",wdl:"D"},{date:"Jun 25",vs:"Ivory Coast",score:"0-2",wdl:"L"}],
        next:[] },
    "Ivory Coast": { name:"Ivory Coast", group:"E", qualifyPct:100,
        played:[{date:"Jun 14",vs:"Ecuador",score:"1-0",wdl:"W"},{date:"Jun 20",vs:"Germany",score:"1-2",wdl:"L"},{date:"Jun 25",vs:"Curaçao",score:"2-0",wdl:"W"}],
        next:[] },

    // ── Group F ─────────────────────────────────────────────────────────────
    "Netherlands": { name:"Netherlands", group:"F", pot:1, qualifyPct:100,
        played:[{date:"Jun 14",vs:"Japan",score:"2-2",wdl:"D"},{date:"Jun 20",vs:"Sweden",score:"5-1",wdl:"W"},{date:"Jun 25",vs:"Tunisia",score:"3-1",wdl:"W"}],
        next:[] },
    "Japan": { name:"Japan", group:"F", pot:2, qualifyPct:100,
        played:[{date:"Jun 14",vs:"Netherlands",score:"2-2",wdl:"D"},{date:"Jun 20",vs:"Tunisia",score:"4-0",wdl:"W"},{date:"Jun 25",vs:"Sweden",score:"1-1",wdl:"D"}],
        next:[] },
    "Tunisia": { name:"Tunisia", group:"F", pot:3, qualifyPct:0,
        played:[{date:"Jun 14",vs:"Sweden",score:"1-5",wdl:"L"},{date:"Jun 20",vs:"Japan",score:"0-4",wdl:"L"},{date:"Jun 25",vs:"Netherlands",score:"1-3",wdl:"L"}],
        next:[] },
    "Sweden": { name:"Sweden", group:"F", qualifyPct:70,
        played:[{date:"Jun 14",vs:"Tunisia",score:"5-1",wdl:"W"},{date:"Jun 20",vs:"Netherlands",score:"1-5",wdl:"L"},{date:"Jun 25",vs:"Japan",score:"1-1",wdl:"D"}],
        next:[] },

    // ── Group G ─────────────────────────────────────────────────────────────
    "Belgium": { name:"Belgium", group:"G", pot:1, qualifyPct:100,
        played:[{date:"Jun 15",vs:"Egypt",score:"1-1",wdl:"D"},{date:"Jun 21",vs:"Iran",score:"0-0",wdl:"D"},{date:"Jun 26",vs:"New Zealand",score:"5-1",wdl:"W"}],
        next:[] },
    "Egypt": { name:"Egypt", group:"G", pot:3, qualifyPct:100,
        played:[{date:"Jun 15",vs:"Belgium",score:"1-1",wdl:"D"},{date:"Jun 21",vs:"New Zealand",score:"3-1",wdl:"W"},{date:"Jun 26",vs:"Iran",score:"1-1",wdl:"D"}],
        next:[] },
    "New Zealand": { name:"New Zealand", group:"G", pot:4, qualifyPct:0,
        played:[{date:"Jun 15",vs:"Iran",score:"2-2",wdl:"D"},{date:"Jun 21",vs:"Egypt",score:"1-3",wdl:"L"},{date:"Jun 26",vs:"Belgium",score:"1-5",wdl:"L"}],
        next:[] },
    "Iran": { name:"Iran", group:"G", qualifyPct:45,
        played:[{date:"Jun 15",vs:"New Zealand",score:"2-2",wdl:"D"},{date:"Jun 21",vs:"Belgium",score:"0-0",wdl:"D"},{date:"Jun 26",vs:"Egypt",score:"1-1",wdl:"D"}],
        next:[] },

    // ── Group H ─────────────────────────────────────────────────────────────
    "Spain": { name:"Spain", group:"H", pot:1, qualifyPct:100,
        played:[{date:"Jun 15",vs:"Cabo Verde",score:"0-0",wdl:"D"},{date:"Jun 21",vs:"Saudi Arabia",score:"4-0",wdl:"W"},{date:"Jun 26",vs:"Uruguay",score:"1-0",wdl:"W"}],
        next:[] },
    "Uruguay": { name:"Uruguay", group:"H", pot:2, qualifyPct:5,
        played:[{date:"Jun 15",vs:"Saudi Arabia",score:"1-1",wdl:"D"},{date:"Jun 21",vs:"Cabo Verde",score:"2-2",wdl:"D"},{date:"Jun 26",vs:"Spain",score:"0-1",wdl:"L"}],
        next:[] },
    "Cabo Verde": { name:"Cabo Verde", group:"H", pot:4, qualifyPct:100,
        played:[{date:"Jun 15",vs:"Spain",score:"0-0",wdl:"D"},{date:"Jun 21",vs:"Uruguay",score:"2-2",wdl:"D"},{date:"Jun 26",vs:"Saudi Arabia",score:"0-0",wdl:"D"}],
        next:[] },
    "Saudi Arabia": { name:"Saudi Arabia", group:"H", qualifyPct:0,
        played:[{date:"Jun 15",vs:"Uruguay",score:"1-1",wdl:"D"},{date:"Jun 21",vs:"Spain",score:"0-4",wdl:"L"},{date:"Jun 26",vs:"Cabo Verde",score:"0-0",wdl:"D"}],
        next:[] },

    // ── Group I ─────────────────────────────────────────────────────────────
    "France": { name:"France", group:"I", pot:1, qualifyPct:100,
        played:[{date:"Jun 16",vs:"Senegal",score:"3-1",wdl:"W"},{date:"Jun 22",vs:"Iraq",score:"3-0",wdl:"W"},{date:"Jun 26",vs:"Norway",score:"4-1",wdl:"W"}],
        next:[] },
    "Senegal": { name:"Senegal", group:"I", pot:2, qualifyPct:75,
        played:[{date:"Jun 16",vs:"France",score:"1-3",wdl:"L"},{date:"Jun 22",vs:"Norway",score:"2-3",wdl:"L"},{date:"Jun 26",vs:"Iraq",score:"5-0",wdl:"W"}],
        next:[] },
    "Norway": { name:"Norway", group:"I", pot:3, qualifyPct:100,
        played:[{date:"Jun 16",vs:"Iraq",score:"4-1",wdl:"W"},{date:"Jun 22",vs:"Senegal",score:"3-2",wdl:"W"},{date:"Jun 26",vs:"France",score:"1-4",wdl:"L"}],
        next:[] },
    "Iraq": { name:"Iraq", group:"I", pot:4, qualifyPct:0,
        played:[{date:"Jun 16",vs:"Norway",score:"1-4",wdl:"L"},{date:"Jun 22",vs:"France",score:"0-3",wdl:"L"},{date:"Jun 26",vs:"Senegal",score:"0-5",wdl:"L"}],
        next:[] },

    // ── Group J ─────────────────────────────────────────────────────────────
    "Argentina": { name:"Argentina", group:"J", pot:1, qualifyPct:100,
        played:[{date:"Jun 16",vs:"Algeria",score:"3-0",wdl:"W"},{date:"Jun 22",vs:"Austria",score:"2-0",wdl:"W"}],
        next:[{date:"Jun 27",vs:"Jordan"}] },
    "Austria": { name:"Austria", group:"J", pot:2, qualifyPct:96,
        played:[{date:"Jun 16",vs:"Jordan",score:"3-1",wdl:"W"},{date:"Jun 22",vs:"Argentina",score:"0-2",wdl:"L"}],
        next:[{date:"Jun 27",vs:"Algeria"}] },
    "Algeria": { name:"Algeria", group:"J", pot:3, qualifyPct:86,
        played:[{date:"Jun 16",vs:"Argentina",score:"0-3",wdl:"L"},{date:"Jun 22",vs:"Jordan",score:"2-1",wdl:"W"}],
        next:[{date:"Jun 27",vs:"Austria"}] },
    "Jordan": { name:"Jordan", group:"J", pot:4, qualifyPct:0,
        played:[{date:"Jun 16",vs:"Austria",score:"1-3",wdl:"L"},{date:"Jun 22",vs:"Algeria",score:"1-2",wdl:"L"}],
        next:[{date:"Jun 27",vs:"Argentina"}] },

    // ── Group K ─────────────────────────────────────────────────────────────
    "Portugal": { name:"Portugal", group:"K", pot:1, qualifyPct:100,
        played:[{date:"Jun 17",vs:"DR Congo",score:"1-1",wdl:"D"},{date:"Jun 23",vs:"Uzbekistan",score:"5-0",wdl:"W"}],
        next:[{date:"Jun 27",vs:"Colombia"}] },
    "DR Congo": { name:"DR Congo", group:"K", pot:4, qualifyPct:40,
        played:[{date:"Jun 17",vs:"Portugal",score:"1-1",wdl:"D"},{date:"Jun 23",vs:"Colombia",score:"0-1",wdl:"L"}],
        next:[{date:"Jun 27",vs:"Uzbekistan"}] },
    "Uzbekistan": { name:"Uzbekistan", group:"K", pot:3, qualifyPct:5,
        played:[{date:"Jun 17",vs:"Colombia",score:"1-3",wdl:"L"},{date:"Jun 23",vs:"Portugal",score:"0-5",wdl:"L"}],
        next:[{date:"Jun 27",vs:"DR Congo"}] },
    "Colombia": { name:"Colombia", group:"K", qualifyPct:100,
        played:[{date:"Jun 17",vs:"Uzbekistan",score:"3-1",wdl:"W"},{date:"Jun 23",vs:"DR Congo",score:"1-0",wdl:"W"}],
        next:[{date:"Jun 27",vs:"Portugal"}] },

    // ── Group L ─────────────────────────────────────────────────────────────
    "England": { name:"England", group:"L", pot:1, qualifyPct:100,
        played:[{date:"Jun 17",vs:"Croatia",score:"4-2",wdl:"W"},{date:"Jun 23",vs:"Ghana",score:"0-0",wdl:"D"}],
        next:[{date:"Jun 27",vs:"Panama"}] },
    "Croatia": { name:"Croatia", group:"L", pot:2, qualifyPct:80,
        played:[{date:"Jun 17",vs:"England",score:"2-4",wdl:"L"},{date:"Jun 23",vs:"Panama",score:"1-0",wdl:"W"}],
        next:[{date:"Jun 27",vs:"Ghana"}] },
    "Ghana": { name:"Ghana", group:"L", pot:4, qualifyPct:87,
        played:[{date:"Jun 17",vs:"Panama",score:"1-0",wdl:"W"},{date:"Jun 23",vs:"England",score:"0-0",wdl:"D"}],
        next:[{date:"Jun 27",vs:"Croatia"}] },
    "Panama": { name:"Panama", group:"L", qualifyPct:0,
        played:[{date:"Jun 17",vs:"Ghana",score:"0-1",wdl:"L"},{date:"Jun 23",vs:"Croatia",score:"0-1",wdl:"L"}],
        next:[{date:"Jun 27",vs:"England"}] },
};
