// teams.js — single source of truth for all match data
// Update qualifyPct, played, next, and LAST_UPDATED here only.
// scoreboard.html and worst.html both load this file.

const LAST_UPDATED = "22 มิ.ย. 2026";

const teamByName = {
    // ── Group A ─────────────────────────────────────────────────────────────
    "South Africa": { name:"South Africa", group:"A", pot:3, qualifyPct:18,
        played:[{date:"Jun 11",vs:"Mexico",score:"0-2",wdl:"L"},{date:"Jun 18",vs:"Czech Republic",score:"1-1",wdl:"D"}],
        next:[{date:"Jun 24",vs:"South Korea"}] },
    "Mexico": { name:"Mexico", group:"A", qualifyPct:100,
        played:[{date:"Jun 11",vs:"South Africa",score:"2-0",wdl:"W"},{date:"Jun 18",vs:"South Korea",score:"1-0",wdl:"W"}],
        next:[{date:"Jun 24",vs:"Czechia"}] },
    "South Korea": { name:"South Korea", group:"A", qualifyPct:95,
        played:[{date:"Jun 11",vs:"Czechia",score:"2-1",wdl:"W"},{date:"Jun 18",vs:"Mexico",score:"0-1",wdl:"L"}],
        next:[{date:"Jun 24",vs:"South Africa"}] },
    "Czechia": { name:"Czechia", group:"A", qualifyPct:33,
        played:[{date:"Jun 11",vs:"South Korea",score:"1-2",wdl:"L"},{date:"Jun 18",vs:"South Africa",score:"1-1",wdl:"D"}],
        next:[{date:"Jun 24",vs:"Mexico"}] },

    // ── Group B ─────────────────────────────────────────────────────────────
    "Qatar": { name:"Qatar", group:"B", pot:3, qualifyPct:5,
        played:[{date:"Jun 12",vs:"Switzerland",score:"1-1",wdl:"D"},{date:"Jun 18",vs:"Canada",score:"0-6",wdl:"L"}],
        next:[{date:"Jun 24",vs:"Bosnia"}] },
    "Switzerland": { name:"Switzerland", group:"B", pot:2, qualifyPct:100,
        played:[{date:"Jun 12",vs:"Qatar",score:"1-1",wdl:"D"},{date:"Jun 18",vs:"Bosnia",score:"4-1",wdl:"W"}],
        next:[{date:"Jun 24",vs:"Canada"}] },
    "Canada": { name:"Canada", group:"B", qualifyPct:100,
        played:[{date:"Jun 12",vs:"Bosnia",score:"1-1",wdl:"D"},{date:"Jun 18",vs:"Qatar",score:"6-0",wdl:"W"}],
        next:[{date:"Jun 24",vs:"Switzerland"}] },
    "Bosnia": { name:"Bosnia", group:"B", qualifyPct:18,
        played:[{date:"Jun 12",vs:"Canada",score:"1-1",wdl:"D"},{date:"Jun 18",vs:"Switzerland",score:"1-4",wdl:"L"}],
        next:[{date:"Jun 24",vs:"Qatar"}] },

    // ── Group C ─────────────────────────────────────────────────────────────
    "Brazil": { name:"Brazil", group:"C", pot:1, qualifyPct:99,
        played:[{date:"Jun 13",vs:"Morocco",score:"1-1",wdl:"D"},{date:"Jun 19",vs:"Haiti",score:"3-0",wdl:"W"}],
        next:[{date:"Jun 24",vs:"Scotland"}] },
    "Scotland": { name:"Scotland", group:"C", pot:3, qualifyPct:75,
        played:[{date:"Jun 13",vs:"Haiti",score:"1-0",wdl:"W"},{date:"Jun 19",vs:"Morocco",score:"0-1",wdl:"L"}],
        next:[{date:"Jun 24",vs:"Brazil"}] },
    "Morocco": { name:"Morocco", group:"C", pot:2, qualifyPct:95,
        played:[{date:"Jun 13",vs:"Brazil",score:"1-1",wdl:"D"},{date:"Jun 19",vs:"Scotland",score:"1-0",wdl:"W"}],
        next:[{date:"Jun 24",vs:"Haiti"}] },
    "Haiti": { name:"Haiti", group:"C", pot:4, qualifyPct:0,
        played:[{date:"Jun 13",vs:"Scotland",score:"0-1",wdl:"L"},{date:"Jun 19",vs:"Brazil",score:"0-3",wdl:"L"}],
        next:[{date:"Jun 24",vs:"Morocco"}] },

    // ── Group D ─────────────────────────────────────────────────────────────
    "Australia": { name:"Australia", group:"D", pot:2, qualifyPct:92,
        played:[{date:"Jun 13",vs:"Turkey",score:"2-0",wdl:"W"},{date:"Jun 19",vs:"USA",score:"0-2",wdl:"L"}],
        next:[{date:"Jun 25",vs:"Paraguay"}] },
    "Turkey": { name:"Turkey", group:"D", pot:4, qualifyPct:0,
        played:[{date:"Jun 13",vs:"Australia",score:"0-2",wdl:"L"},{date:"Jun 19",vs:"Paraguay",score:"0-1",wdl:"L"}],
        next:[{date:"Jun 25",vs:"USA"}] },
    "Paraguay": { name:"Paraguay", group:"D", pot:3, qualifyPct:87,
        played:[{date:"Jun 12",vs:"USA",score:"1-4",wdl:"L"},{date:"Jun 19",vs:"Turkey",score:"1-0",wdl:"W"}],
        next:[{date:"Jun 25",vs:"Australia"}] },
    "USA": { name:"USA", group:"D", qualifyPct:100,
        played:[{date:"Jun 12",vs:"Paraguay",score:"4-1",wdl:"W"},{date:"Jun 19",vs:"Australia",score:"2-0",wdl:"W"}],
        next:[{date:"Jun 25",vs:"Turkey"}] },

    // ── Group E ─────────────────────────────────────────────────────────────
    "Germany": { name:"Germany", group:"E", pot:1, qualifyPct:100,
        played:[{date:"Jun 14",vs:"Curaçao",score:"7-1",wdl:"W"},{date:"Jun 20",vs:"Ivory Coast",score:"2-1",wdl:"W"}],
        next:[{date:"Jun 25",vs:"Ecuador"}] },
    "Ecuador": { name:"Ecuador", group:"E", pot:2, qualifyPct:25,
        played:[{date:"Jun 14",vs:"Ivory Coast",score:"0-1",wdl:"L"},{date:"Jun 20",vs:"Curaçao",score:"0-0",wdl:"D"}],
        next:[{date:"Jun 25",vs:"Germany"}] },
    "Curaçao": { name:"Curaçao", group:"E", pot:4, qualifyPct:6,
        played:[{date:"Jun 14",vs:"Germany",score:"1-7",wdl:"L"},{date:"Jun 20",vs:"Ecuador",score:"0-0",wdl:"D"}],
        next:[{date:"Jun 25",vs:"Ivory Coast"}] },
    "Ivory Coast": { name:"Ivory Coast", group:"E", qualifyPct:99,
        played:[{date:"Jun 14",vs:"Ecuador",score:"1-0",wdl:"W"},{date:"Jun 20",vs:"Germany",score:"1-2",wdl:"L"}],
        next:[{date:"Jun 25",vs:"Curaçao"}] },

    // ── Group F ─────────────────────────────────────────────────────────────
    "Netherlands": { name:"Netherlands", group:"F", pot:1, qualifyPct:93,
        played:[{date:"Jun 14",vs:"Japan",score:"2-2",wdl:"D"},{date:"Jun 20",vs:"Sweden",score:"5-1",wdl:"W"}],
        next:[{date:"Jun 25",vs:"Tunisia"}] },
    "Japan": { name:"Japan", group:"F", pot:2, qualifyPct:87,
        played:[{date:"Jun 14",vs:"Netherlands",score:"2-2",wdl:"D"},{date:"Jun 20",vs:"Tunisia",score:"4-0",wdl:"W"}],
        next:[{date:"Jun 25",vs:"Sweden"}] },
    "Tunisia": { name:"Tunisia", group:"F", pot:3, qualifyPct:5,
        played:[{date:"Jun 14",vs:"Sweden",score:"1-5",wdl:"L"},{date:"Jun 20",vs:"Japan",score:"0-4",wdl:"L"}],
        next:[{date:"Jun 25",vs:"Netherlands"}] },
    "Sweden": { name:"Sweden", group:"F", qualifyPct:98,
        played:[{date:"Jun 14",vs:"Tunisia",score:"5-1",wdl:"W"},{date:"Jun 20",vs:"Netherlands",score:"1-5",wdl:"L"}],
        next:[{date:"Jun 25",vs:"Japan"}] },

    // ── Group G ─────────────────────────────────────────────────────────────
    "Belgium": { name:"Belgium", group:"G", pot:1, qualifyPct:96,
        played:[{date:"Jun 15",vs:"Egypt",score:"1-1",wdl:"D"},{date:"Jun 21",vs:"Iran",score:"0-0",wdl:"D"}],
        next:[{date:"Jun 26",vs:"New Zealand"}] },
    "Egypt": { name:"Egypt", group:"G", pot:3, qualifyPct:87,
        played:[{date:"Jun 15",vs:"Belgium",score:"1-1",wdl:"D"},{date:"Jun 21",vs:"New Zealand",score:"3-1",wdl:"W"}],
        next:[{date:"Jun 26",vs:"Iran"}] },
    "New Zealand": { name:"New Zealand", group:"G", pot:4, qualifyPct:31,
        played:[{date:"Jun 15",vs:"Iran",score:"2-2",wdl:"D"},{date:"Jun 21",vs:"Egypt",score:"1-3",wdl:"L"}],
        next:[{date:"Jun 26",vs:"Belgium"}] },
    "Iran": { name:"Iran", group:"G", qualifyPct:53,
        played:[{date:"Jun 15",vs:"New Zealand",score:"2-2",wdl:"D"},{date:"Jun 21",vs:"Belgium",score:"0-0",wdl:"D"}],
        next:[{date:"Jun 26",vs:"Egypt"}] },

    // ── Group H ─────────────────────────────────────────────────────────────
    "Spain": { name:"Spain", group:"H", pot:1, qualifyPct:99,
        played:[{date:"Jun 15",vs:"Cabo Verde",score:"0-0",wdl:"D"},{date:"Jun 21",vs:"Saudi Arabia",score:"4-0",wdl:"W"}],
        next:[{date:"Jun 26",vs:"Uruguay"}] },
    "Uruguay": { name:"Uruguay", group:"H", pot:2, qualifyPct:80,
        played:[{date:"Jun 15",vs:"Saudi Arabia",score:"1-1",wdl:"D"},{date:"Jun 21",vs:"Cabo Verde",score:"2-2",wdl:"D"}],
        next:[{date:"Jun 26",vs:"Spain"}] },
    "Cabo Verde": { name:"Cabo Verde", group:"H", pot:4, qualifyPct:52,
        played:[{date:"Jun 15",vs:"Spain",score:"0-0",wdl:"D"},{date:"Jun 21",vs:"Uruguay",score:"2-2",wdl:"D"}],
        next:[{date:"Jun 26",vs:"Saudi Arabia"}] },
    "Saudi Arabia": { name:"Saudi Arabia", group:"H", qualifyPct:42,
        played:[{date:"Jun 15",vs:"Uruguay",score:"1-1",wdl:"D"},{date:"Jun 21",vs:"Spain",score:"0-4",wdl:"L"}],
        next:[{date:"Jun 26",vs:"Cabo Verde"}] },

    // ── Group I ─────────────────────────────────────────────────────────────
    "France": { name:"France", group:"I", pot:1, qualifyPct:98,
        played:[{date:"Jun 16",vs:"Senegal",score:"3-1",wdl:"W"}],
        next:[{date:"Jun 22",vs:"Iraq"},{date:"Jun 26",vs:"Norway"}] },
    "Senegal": { name:"Senegal", group:"I", pot:2, qualifyPct:67,
        played:[{date:"Jun 16",vs:"France",score:"1-3",wdl:"L"}],
        next:[{date:"Jun 22",vs:"Norway"},{date:"Jun 26",vs:"Iraq"}] },
    "Norway": { name:"Norway", group:"I", pot:3, qualifyPct:99,
        played:[{date:"Jun 16",vs:"Iraq",score:"4-1",wdl:"W"}],
        next:[{date:"Jun 22",vs:"Senegal"},{date:"Jun 26",vs:"France"}] },
    "Iraq": { name:"Iraq", group:"I", pot:4, qualifyPct:8,
        played:[{date:"Jun 16",vs:"Norway",score:"1-4",wdl:"L"}],
        next:[{date:"Jun 22",vs:"France"},{date:"Jun 26",vs:"Senegal"}] },

    // ── Group J ─────────────────────────────────────────────────────────────
    "Argentina": { name:"Argentina", group:"J", pot:1, qualifyPct:99,
        played:[{date:"Jun 16",vs:"Algeria",score:"3-0",wdl:"W"}],
        next:[{date:"Jun 22",vs:"Austria"},{date:"Jun 27",vs:"Jordan"}] },
    "Austria": { name:"Austria", group:"J", pot:2, qualifyPct:96,
        played:[{date:"Jun 16",vs:"Jordan",score:"3-1",wdl:"W"}],
        next:[{date:"Jun 22",vs:"Argentina"},{date:"Jun 27",vs:"Algeria"}] },
    "Algeria": { name:"Algeria", group:"J", pot:3, qualifyPct:63,
        played:[{date:"Jun 16",vs:"Argentina",score:"0-3",wdl:"L"}],
        next:[{date:"Jun 22",vs:"Jordan"},{date:"Jun 27",vs:"Austria"}] },
    "Jordan": { name:"Jordan", group:"J", pot:4, qualifyPct:9,
        played:[{date:"Jun 16",vs:"Austria",score:"1-3",wdl:"L"}],
        next:[{date:"Jun 22",vs:"Algeria"},{date:"Jun 27",vs:"Argentina"}] },

    // ── Group K ─────────────────────────────────────────────────────────────
    "Portugal": { name:"Portugal", group:"K", pot:1, qualifyPct:98,
        played:[{date:"Jun 17",vs:"DR Congo",score:"1-1",wdl:"D"}],
        next:[{date:"Jun 23",vs:"Uzbekistan"},{date:"Jun 27",vs:"Colombia"}] },
    "DR Congo": { name:"DR Congo", group:"K", pot:4, qualifyPct:50,
        played:[{date:"Jun 17",vs:"Portugal",score:"1-1",wdl:"D"}],
        next:[{date:"Jun 23",vs:"Colombia"},{date:"Jun 27",vs:"Uzbekistan"}] },
    "Uzbekistan": { name:"Uzbekistan", group:"K", pot:3, qualifyPct:36,
        played:[{date:"Jun 17",vs:"Colombia",score:"1-3",wdl:"L"}],
        next:[{date:"Jun 23",vs:"Portugal"},{date:"Jun 27",vs:"DR Congo"}] },
    "Colombia": { name:"Colombia", group:"K", qualifyPct:91,
        played:[{date:"Jun 17",vs:"Uzbekistan",score:"3-1",wdl:"W"}],
        next:[{date:"Jun 23",vs:"DR Congo"},{date:"Jun 27",vs:"Portugal"}] },

    // ── Group L ─────────────────────────────────────────────────────────────
    "England": { name:"England", group:"L", pot:1, qualifyPct:99,
        played:[{date:"Jun 17",vs:"Croatia",score:"4-2",wdl:"W"}],
        next:[{date:"Jun 23",vs:"Ghana"},{date:"Jun 27",vs:"Panama"}] },
    "Croatia": { name:"Croatia", group:"L", pot:2, qualifyPct:76,
        played:[{date:"Jun 17",vs:"England",score:"2-4",wdl:"L"}],
        next:[{date:"Jun 23",vs:"Panama"},{date:"Jun 27",vs:"Ghana"}] },
    "Ghana": { name:"Ghana", group:"L", pot:4, qualifyPct:80,
        played:[{date:"Jun 17",vs:"Panama",score:"1-0",wdl:"W"}],
        next:[{date:"Jun 23",vs:"England"},{date:"Jun 27",vs:"Croatia"}] },
    "Panama": { name:"Panama", group:"L", qualifyPct:14,
        played:[{date:"Jun 17",vs:"Ghana",score:"0-1",wdl:"L"}],
        next:[{date:"Jun 23",vs:"Croatia"},{date:"Jun 27",vs:"England"}] },
};
